# Generated by Django 4.2.6 on 2023-11-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_ad_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
