# Generated by Django 4.2.6 on 2023-11-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_delete_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
